[package]
name = "Hippius"
version = "0.1.91"
description = "Hippius Desktop App"
authors = ["you"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tauri_project_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [
    "protocol-asset",
    'tray-icon',
    'image-ico',
    'image-png',
    'devtools',
] }
tauri-plugin-opener = "2"
tauri-plugin-deep-link = "2.0.0"
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
tokio = { version = "1.49.0", features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "time",
    "fs",
    "io-util",
    "net",
    "process",
    "signal",
] }
futures = "0.3"
dirs = "6.0.0"
flate2 = "1.1.2"
tar = "0.4.44"
reqwest = { version = "0.13.1", default-features = false, features = [
    "blocking",
    "multipart",
    "json",
    "stream",
    "rustls",
] }
aws-sdk-s3 = { version = "1.125.0", features = ["behavior-version-latest"] }
aws-credential-types = { version = "1.2.14", features = [
    "hardcoded-credentials",
] }
zip = "4.2.0"
dotenvy = "0.15"
base64 = "0.21"
sha2 = "0.10"
aes = "0.8"
cbc = "0.1"
md5 = "0.7"
subxt = { version = "0.38", features = ["substrate-compat"] }
sp-core = "34.0.0"
uuid = { version = "1", features = ["v4"] }
tempfile = "3"
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio-native-tls"] }
hex = "0.4"
parity-scale-codec = "3.6"
tauri-plugin-fs = "2"
sysinfo = "0.32"
notify = "6.1"
tauri-plugin-dialog = "2.6.0"
tauri-plugin-http = { version = "2", features = ["unsafe-headers"] }
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8"
tauri-plugin-process = "2"
which = "4.4"
hostname = "0.4"
zeroize = "1"
bip39 = { version = "2.2", features = ["rand"] }
alloy-signer = { version = "0.8", default-features = false }
alloy-signer-local = { version = "0.8", default-features = false, features = [
    "mnemonic",
] }
hcfs-client = { git = "ssh://git@github.com/thenervelab/hcfs.git", rev = "2c5e5b2" }
hcfs-shared = { git = "ssh://git@github.com/thenervelab/hcfs.git", rev = "2c5e5b2" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.31.2", features = ["fs"] }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.25"
objc = "0.2"

[target."cfg(any(target_os = \"macos\", windows, target_os = \"linux\"))".dependencies]
tauri-plugin-single-instance = { version = "2.0.0", features = ["deep-link"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = { version = "2", default-features = false, features = [
    "rustls-tls",
] }
# Directory Traversal
walkdir = "2.5"
# Ergonomic Error Handling
anyhow = "1.0"

[dev-dependencies]
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "time",
    "process",
] }
anyhow = "1"
reqwest = { version = "0.13.1", default-features = false, features = [
    "json",
    "rustls",
] }
rand = "0.10.0"
tempfile = "3"
uuid = { version = "1", features = ["v4"] }
axum = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
