//! Tauri IPC surface for the local-wallet feature.
//!
//! All persistence commands are scoped to the currently-logged-in account.
//! Every command that touches the DB starts with [`require_owner`] to:
//!   1. Refuse the call cleanly when no user is logged in (the FE listens
//!      for this and renders the "log in to manage wallets" empty state).
//!   2. Translate `AuthInfo.substrate_address` into the same `account_key`
//!      hash that `sync_paths` uses, so a multi-account install keeps each
//!      user's wallets isolated by `owner` column.
//!
//! Stateless mnemonic helpers (`generate_mnemonic`, `validate_mnemonic`,
//! `derive_address`) deliberately skip the gate — they don't read or
//! write the DB and the FE uses them during the pre-create preview.

use crate::app_state::AppState;
use crate::auth::account_key::account_key;
use crate::error::AppError;
use crate::wallet::crypto;
use crate::wallet::repo::{self, LocalWallet, PublicLocalWallet};
use serde::Serialize;
use subxt_signer::{
    bip39::Mnemonic as SubxtMnemonic,
    sr25519::Keypair as SrKeypair,
};
use tauri::State;
use tracing::info;

/// Resolve the active account's owner key, or return a friendly error the
/// FE can show when no one is logged in.
///
/// Wrapping `current_account_id`'s `Result<_, String>` into `AppError`
/// here keeps every command body a one-liner instead of duplicating the
/// `map_err` dance.
fn require_owner(state: &State<'_, AppState>) -> Result<String, AppError> {
    let account_id = state
        .current_account_id()
        .map_err(|_| AppError::Other("Log in to manage local wallets".into()))?;
    Ok(account_key(&account_id))
}

/// Derive a polkadot SS58 address from a BIP-39 mnemonic. Used both
/// internally (during create/import) and from the FE for previewing.
fn derive_address(mnemonic: &str) -> Result<String, AppError> {
    let parsed = SubxtMnemonic::parse(mnemonic).map_err(|e| AppError::Other(format!("Invalid BIP-39 mnemonic: {e}")))?;
    let pair = SrKeypair::from_phrase(&parsed, None).map_err(|e| AppError::Other(format!("Failed to derive sr25519 keypair: {e}")))?;
    Ok(pair.public_key().to_account_id().to_string())
}

/// Generate a fresh 12-word mnemonic. The mnemonic is returned to the FE
/// only so the user can write it down during the create flow — it must be
/// immediately re-submitted via `create` (along with the password) to be
/// stored encrypted; nothing in Rust holds onto it.
#[tauri::command]
pub fn local_wallet_generate_mnemonic() -> Result<String, AppError> {
    let mnemonic = bip39::Mnemonic::generate(12).map_err(|e| AppError::Other(format!("bip39 generate failed: {e}")))?;
    Ok(mnemonic.to_string())
}

/// Cheap mnemonic validity check the FE uses to decide whether to enable
/// the "Continue" button on the import screen.
#[tauri::command]
pub fn local_wallet_validate_mnemonic(mnemonic: String) -> bool {
    bip39::Mnemonic::parse_normalized(&mnemonic).is_ok()
}

/// Derive an address from a mnemonic without persisting anything.
/// Surfaces address previews on the import / create-confirm screens.
#[tauri::command]
pub fn local_wallet_derive_address(mnemonic: String) -> Result<String, AppError> {
    derive_address(&mnemonic)
}

/// List every wallet owned by the active account, secrets stripped. Sorted
/// by creation time ascending (oldest first) so the active-wallet selector
/// renders deterministically.
#[tauri::command]
pub async fn local_wallet_list(state: State<'_, AppState>) -> Result<Vec<PublicLocalWallet>, AppError> {
    let owner = require_owner(&state)?;
    let pool = state.pool()?;
    let rows = repo::list_all(pool, &owner).await?;
    Ok(rows.iter().map(PublicLocalWallet::from).collect())
}

/// Return whether the active account has any wallets. Cheaper than `list`
/// for the onboarding gate which only cares about presence.
#[tauri::command]
pub async fn local_wallet_has_any(state: State<'_, AppState>) -> Result<bool, AppError> {
    let owner = require_owner(&state)?;
    let pool = state.pool()?;
    Ok(repo::count_for_owner(pool, &owner).await? > 0)
}

/// Return the active account's active wallet, secrets stripped. `None` if
/// the account has no wallets at all.
#[tauri::command]
pub async fn local_wallet_get_active(state: State<'_, AppState>) -> Result<Option<PublicLocalWallet>, AppError> {
    let owner = require_owner(&state)?;
    let pool = state.pool()?;
    Ok(repo::get_active(pool, &owner).await?.as_ref().map(PublicLocalWallet::from))
}

/// Create a new wallet from a mnemonic. The mnemonic is encrypted under
/// `password` at rest and a SHA-256(password || address) hash is stored
/// alongside for verification on unlock.
///
/// The mnemonic argument may be either freshly generated by
/// `local_wallet_generate_mnemonic` or pasted by the user during import —
/// the two paths are identical from Rust's perspective. The row is scoped
/// to whichever account is currently logged in.
#[tauri::command]
pub async fn local_wallet_create(state: State<'_, AppState>, name: String, mnemonic: String, password: String) -> Result<PublicLocalWallet, AppError> {
    if bip39::Mnemonic::parse_normalized(&mnemonic).is_err() {
        return Err(AppError::Other("Invalid mnemonic".into()));
    }
    if name.trim().is_empty() {
        return Err(AppError::Other("Wallet name is required".into()));
    }
    if password.is_empty() {
        return Err(AppError::Other("Password is required".into()));
    }

    let owner = require_owner(&state)?;
    let address = derive_address(&mnemonic)?;
    let encrypted = crypto::encrypt_mnemonic(&mnemonic, &password, &address)?;
    let pw_hash = crypto::password_hash(&password, &address);

    let pool = state.pool()?;
    let row = repo::insert(pool, &owner, name.trim(), &address, &encrypted, &pw_hash).await?;
    info!(wallet = %row.address, "Local wallet created");
    Ok(PublicLocalWallet::from(&row))
}

/// Mark a wallet active. The previous active wallet for this owner (if
/// any) is transactionally cleared first so the "exactly one active per
/// owner" invariant holds throughout.
#[tauri::command]
pub async fn local_wallet_set_active(state: State<'_, AppState>, id: i64) -> Result<(), AppError> {
    let owner = require_owner(&state)?;
    let pool = state.pool()?;
    if repo::get_by_id(pool, &owner, id).await?.is_none() {
        return Err(AppError::Other(format!("Wallet {id} not found")));
    }
    repo::set_active(pool, &owner, id).await?;
    Ok(())
}

#[tauri::command]
pub async fn local_wallet_rename(state: State<'_, AppState>, id: i64, name: String) -> Result<(), AppError> {
    if name.trim().is_empty() {
        return Err(AppError::Other("Wallet name is required".into()));
    }
    let owner = require_owner(&state)?;
    let pool = state.pool()?;
    repo::rename(pool, &owner, id, name.trim()).await?;
    Ok(())
}

#[tauri::command]
pub async fn local_wallet_delete(state: State<'_, AppState>, id: i64) -> Result<(), AppError> {
    let owner = require_owner(&state)?;
    let pool = state.pool()?;
    repo::delete(pool, &owner, id).await?;
    Ok(())
}

/// Verify the user typed the correct password for a wallet without
/// surfacing the mnemonic. Used by the unlock-on-action UX pattern in
/// the FE (the password prompt before signing).
#[tauri::command]
pub async fn local_wallet_verify_password(state: State<'_, AppState>, id: i64, password: String) -> Result<bool, AppError> {
    let owner = require_owner(&state)?;
    let pool = state.pool()?;
    let wallet = match repo::get_by_id(pool, &owner, id).await? {
        Some(w) => w,
        None => return Err(AppError::Other(format!("Wallet {id} not found"))),
    };
    let expected = crypto::password_hash(&password, &wallet.address);
    Ok(constant_time_eq(expected.as_bytes(), wallet.password_hash.as_bytes()))
}

/// Decrypt and return a wallet's mnemonic. The FE uses this on the
/// "view recovery phrase" screen after the user re-types their password.
/// Wrong password yields `Err` (the AEAD tag mismatch is indistinguishable
/// from corrupt data at the API surface).
#[tauri::command]
pub async fn local_wallet_get_decrypted_mnemonic(state: State<'_, AppState>, id: i64, password: String) -> Result<String, AppError> {
    let owner = require_owner(&state)?;
    let pool = state.pool()?;
    let wallet = match repo::get_by_id(pool, &owner, id).await? {
        Some(w) => w,
        None => return Err(AppError::Other(format!("Wallet {id} not found"))),
    };
    // Hash check first for a friendlier error than AEAD-decrypt-failed.
    let expected = crypto::password_hash(&password, &wallet.address);
    if !constant_time_eq(expected.as_bytes(), wallet.password_hash.as_bytes()) {
        return Err(AppError::Other("Incorrect password".into()));
    }
    let plain = crypto::decrypt_mnemonic(&wallet.encrypted_mnemonic, &password, &wallet.address)?;
    Ok(plain.as_str().to_owned())
}

/// Exported backup payload. The FE serialises this to a JSON file the
/// user saves to disk. Re-importing on another device uses
/// `local_wallet_import_encrypted_backup` below.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct WalletBackup {
    pub name: String,
    pub address: String,
    pub encrypted_mnemonic: String,
    pub password_hash: String,
    pub exported_at: String,
}

#[tauri::command]
pub async fn local_wallet_export_backup(state: State<'_, AppState>, id: i64) -> Result<WalletBackup, AppError> {
    let owner = require_owner(&state)?;
    let pool = state.pool()?;
    let wallet = match repo::get_by_id(pool, &owner, id).await? {
        Some(w) => w,
        None => return Err(AppError::Other(format!("Wallet {id} not found"))),
    };
    use std::time::{SystemTime, UNIX_EPOCH};
    let exported_at = {
        // RFC3339-ish: just emit ms since epoch as a string. The FE displays
        // the file's own mtime so this field is informational only.
        let ms = SystemTime::now().duration_since(UNIX_EPOCH).map(|d| d.as_millis()).unwrap_or(0);
        ms.to_string()
    };
    Ok(WalletBackup {
        name: wallet.name,
        address: wallet.address,
        encrypted_mnemonic: wallet.encrypted_mnemonic,
        password_hash: wallet.password_hash,
        exported_at,
    })
}

/// Import a wallet from the JSON payload produced by `export_backup`. The
/// ciphertext + password hash are stored verbatim — re-encryption is not
/// possible without the password, which the export file does not contain.
/// Stored under the currently-logged-in account.
#[tauri::command]
pub async fn local_wallet_import_encrypted_backup(
    state: State<'_, AppState>,
    name: String,
    address: String,
    encrypted_mnemonic: String,
    password_hash: String,
    password: String,
) -> Result<PublicLocalWallet, AppError> {
    if name.trim().is_empty() {
        return Err(AppError::Other("Wallet name is required".into()));
    }
    if address.trim().is_empty() {
        return Err(AppError::Other("Address is required".into()));
    }
    // Verify the user typed the correct password by recomputing the
    // address-salted SHA-256 hash and constant-time-comparing it to
    // the hash from the backup. Without this we'd happily import the
    // wallet regardless of what the user typed — and they'd then hit
    // "Incorrect password" on the next sign attempt with no clue why.
    let expected = crypto::password_hash(&password, address.trim());
    if !constant_time_eq(expected.as_bytes(), password_hash.as_bytes()) {
        return Err(AppError::Other("Incorrect password for this backup".into()));
    }
    let owner = require_owner(&state)?;
    let pool = state.pool()?;
    let row = repo::insert(pool, &owner, name.trim(), address.trim(), &encrypted_mnemonic, &password_hash).await?;
    Ok(PublicLocalWallet::from(&row))
}

/// Name of the JSON entry inside the wallet backup `.zip`. Kept as a
/// const so the writer and the reader can't drift apart silently.
const BACKUP_ZIP_ENTRY: &str = "wallet-backup.json";

/// Export the active account's wallet `id` as a `.zip` archive whose
/// only entry is `wallet-backup.json` (the same `WalletBackup` payload
/// `local_wallet_export_backup` returns, serialised pretty-printed).
///
/// The archive is **not** zip-encrypted: the JSON inside is already
/// ChaCha20-Poly1305-encrypted under the wallet password (the
/// `encryptedMnemonic` ciphertext), and the password is never escrowed
/// in either the file or the archive. The zip is purely a container
/// chosen to (a) mirror `feature/wallet-updates` for cross-compat with
/// the v1 frontend, and (b) give the FE a single binary blob to write
/// instead of pretty-printed JSON.
#[tauri::command]
pub async fn local_wallet_export_backup_zip(
    state: State<'_, AppState>,
    id: i64,
) -> Result<Vec<u8>, AppError> {
    use std::io::{Cursor, Write};

    let backup = local_wallet_export_backup(state, id).await?;
    let json = serde_json::to_vec_pretty(&serde_json::json!({
        "version": 2,
        "name": backup.name,
        "address": backup.address,
        "encryptedMnemonic": backup.encrypted_mnemonic,
        "passwordHash": backup.password_hash,
        "exportedAt": backup.exported_at,
    }))
    .map_err(|e| AppError::Other(format!("failed to serialise backup json: {e}")))?;

    let buf = Cursor::new(Vec::new());
    let mut zip = zip::ZipWriter::new(buf);
    let options = zip::write::SimpleFileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated);
    zip.start_file(BACKUP_ZIP_ENTRY, options)
        .map_err(|e| AppError::Other(format!("zip start_file: {e}")))?;
    zip.write_all(&json)
        .map_err(|e| AppError::Other(format!("zip write_all: {e}")))?;
    let cursor = zip
        .finish()
        .map_err(|e| AppError::Other(format!("zip finish: {e}")))?;
    Ok(cursor.into_inner())
}

/// Import a wallet from a `.zip` archive produced by
/// [`local_wallet_export_backup_zip`]. Pulls `wallet-backup.json` out of
/// the archive, validates its shape, and persists the row under the
/// currently-logged-in account.
///
/// `name` is the user-supplied label from the import screen — the
/// backup file carries a "name" hint but the FE always lets the user
/// rename on import, and treating the FE-supplied name as authoritative
/// matches the existing JSON-path command (`local_wallet_import_encrypted_backup`).
#[tauri::command]
pub async fn local_wallet_import_encrypted_backup_from_zip(
    state: State<'_, AppState>,
    name: String,
    zip_bytes: Vec<u8>,
    password: String,
) -> Result<PublicLocalWallet, AppError> {
    use std::io::{Cursor, Read};

    if name.trim().is_empty() {
        return Err(AppError::Other("Wallet name is required".into()));
    }

    let reader = Cursor::new(zip_bytes);
    let mut archive = zip::ZipArchive::new(reader)
        .map_err(|e| AppError::Other(format!("Couldn't open backup zip: {e}")))?;

    let mut entry = archive
        .by_name(BACKUP_ZIP_ENTRY)
        .map_err(|_| AppError::Other(format!("Backup zip is missing `{BACKUP_ZIP_ENTRY}`")))?;
    let mut json_bytes = Vec::with_capacity(entry.size() as usize);
    entry
        .read_to_end(&mut json_bytes)
        .map_err(|e| AppError::Other(format!("Couldn't read backup entry: {e}")))?;
    drop(entry);

    let parsed: serde_json::Value = serde_json::from_slice(&json_bytes)
        .map_err(|e| AppError::Other(format!("Backup file isn't valid JSON: {e}")))?;
    let address = parsed
        .get("address")
        .and_then(|v| v.as_str())
        .ok_or_else(|| AppError::Other("Backup is missing `address`".into()))?
        .trim()
        .to_owned();
    let encrypted_mnemonic = parsed
        .get("encryptedMnemonic")
        .or_else(|| parsed.get("encrypted_mnemonic"))
        .and_then(|v| v.as_str())
        .ok_or_else(|| AppError::Other("Backup is missing `encryptedMnemonic`".into()))?
        .to_owned();
    let password_hash = parsed
        .get("passwordHash")
        .or_else(|| parsed.get("password_hash"))
        .and_then(|v| v.as_str())
        .ok_or_else(|| AppError::Other("Backup is missing `passwordHash`".into()))?
        .to_owned();
    if address.is_empty() {
        return Err(AppError::Other("Backup `address` is empty".into()));
    }

    // Same verification as the JSON path: the user's typed password
    // must match the hash baked into the backup, otherwise we'd
    // store a wallet they can't actually sign with.
    let expected = crypto::password_hash(&password, &address);
    if !constant_time_eq(expected.as_bytes(), password_hash.as_bytes()) {
        return Err(AppError::Other("Incorrect password for this backup".into()));
    }

    let owner = require_owner(&state)?;
    let pool = state.pool()?;
    let row = repo::insert(
        pool,
        &owner,
        name.trim(),
        &address,
        &encrypted_mnemonic,
        &password_hash,
    )
    .await?;
    Ok(PublicLocalWallet::from(&row))
}

/// Constant-time equality for two byte slices. SHA-256 hex strings are
/// fixed length so the timing channel from `==` is small in practice, but
/// using constant-time eq makes that explicit.
fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut diff: u8 = 0;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

// Convenience: keep the LocalWallet alias importable from this module so
// downstream code can `use crate::wallet::commands::LocalWallet`.
#[allow(dead_code)]
pub(crate) type _LocalWallet = LocalWallet;
