//! Tauri IPC surface for the local-wallet feature.
//!
//! Every command runs against `state.pool()?` so the schema migration in
//! `utils/schema::ensure_table_schema` is the single creator of the
//! `local_wallets` table. Commands return either `PublicLocalWallet` (no
//! secrets) or a small structured result; the only API that crosses the
//! IPC boundary with the plaintext mnemonic is `get_decrypted_mnemonic`,
//! and even that returns it as the response body, never persists it.

use crate::app_state::AppState;
use crate::error::AppError;
use crate::wallet::crypto;
use crate::wallet::repo::{self, LocalWallet, PublicLocalWallet};
use serde::Serialize;
use subxt_signer::{
    bip39::Mnemonic as SubxtMnemonic,
    sr25519::Keypair as SrKeypair,
};
use tauri::State;
use tracing::info;

/// Derive a polkadot SS58 address from a BIP-39 mnemonic. Used both
/// internally (during create/import) and from the FE for previewing.
fn derive_address(mnemonic: &str) -> Result<String, AppError> {
    let parsed = SubxtMnemonic::parse(mnemonic).map_err(|e| AppError::Other(format!("Invalid BIP-39 mnemonic: {e}")))?;
    let pair = SrKeypair::from_phrase(&parsed, None).map_err(|e| AppError::Other(format!("Failed to derive sr25519 keypair: {e}")))?;
    Ok(pair.public_key().to_account_id().to_string())
}

/// Generate a fresh 12-word mnemonic. The mnemonic is returned to the FE
/// only so the user can write it down during the create flow — it must be
/// immediately re-submitted via `create` (along with the password) to be
/// stored encrypted; nothing in Rust holds onto it.
#[tauri::command]
pub fn local_wallet_generate_mnemonic() -> Result<String, AppError> {
    let mnemonic = bip39::Mnemonic::generate(12).map_err(|e| AppError::Other(format!("bip39 generate failed: {e}")))?;
    Ok(mnemonic.to_string())
}

/// Cheap mnemonic validity check the FE uses to decide whether to enable
/// the "Continue" button on the import screen.
#[tauri::command]
pub fn local_wallet_validate_mnemonic(mnemonic: String) -> bool {
    bip39::Mnemonic::parse_normalized(&mnemonic).is_ok()
}

/// Derive an address from a mnemonic without persisting anything.
/// Surfaces address previews on the import / create-confirm screens.
#[tauri::command]
pub fn local_wallet_derive_address(mnemonic: String) -> Result<String, AppError> {
    derive_address(&mnemonic)
}

/// List every wallet, secrets stripped. Sorted by creation time ascending
/// (oldest first) so the active-wallet selector renders deterministically.
#[tauri::command]
pub async fn local_wallet_list(state: State<'_, AppState>) -> Result<Vec<PublicLocalWallet>, AppError> {
    let pool = state.pool()?;
    let rows = repo::list_all(pool).await?;
    Ok(rows.iter().map(PublicLocalWallet::from).collect())
}

/// Return whether any wallets exist. Cheaper than `list` for the
/// onboarding gate which only cares about presence.
#[tauri::command]
pub async fn local_wallet_has_any(state: State<'_, AppState>) -> Result<bool, AppError> {
    let pool = state.pool()?;
    let count: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM local_wallets").fetch_one(pool).await?;
    Ok(count > 0)
}

/// Return the currently-active wallet, secrets stripped. `None` if no
/// wallets exist at all.
#[tauri::command]
pub async fn local_wallet_get_active(state: State<'_, AppState>) -> Result<Option<PublicLocalWallet>, AppError> {
    let pool = state.pool()?;
    Ok(repo::get_active(pool).await?.as_ref().map(PublicLocalWallet::from))
}

/// Create a new wallet from a mnemonic. The mnemonic is encrypted under
/// `password` at rest and a SHA-256(password || address) hash is stored
/// alongside for verification on unlock.
///
/// The mnemonic argument may be either freshly generated by
/// `local_wallet_generate_mnemonic` or pasted by the user during import —
/// the two paths are identical from Rust's perspective.
#[tauri::command]
pub async fn local_wallet_create(state: State<'_, AppState>, name: String, mnemonic: String, password: String) -> Result<PublicLocalWallet, AppError> {
    if !bip39::Mnemonic::parse_normalized(&mnemonic).is_ok() {
        return Err(AppError::Other("Invalid mnemonic".into()));
    }
    if name.trim().is_empty() {
        return Err(AppError::Other("Wallet name is required".into()));
    }
    if password.is_empty() {
        return Err(AppError::Other("Password is required".into()));
    }

    let address = derive_address(&mnemonic)?;
    let encrypted = crypto::encrypt_mnemonic(&mnemonic, &password, &address)?;
    let pw_hash = crypto::password_hash(&password, &address);

    let pool = state.pool()?;
    let row = repo::insert(pool, name.trim(), &address, &encrypted, &pw_hash).await?;
    info!(wallet = %row.address, "Local wallet created");
    Ok(PublicLocalWallet::from(&row))
}

/// Mark a wallet active. The previous active wallet (if any) is
/// transactionally cleared first so the "exactly one active" invariant
/// holds throughout.
#[tauri::command]
pub async fn local_wallet_set_active(state: State<'_, AppState>, id: i64) -> Result<(), AppError> {
    let pool = state.pool()?;
    if repo::get_by_id(pool, id).await?.is_none() {
        return Err(AppError::Other(format!("Wallet {id} not found")));
    }
    repo::set_active(pool, id).await?;
    Ok(())
}

#[tauri::command]
pub async fn local_wallet_rename(state: State<'_, AppState>, id: i64, name: String) -> Result<(), AppError> {
    if name.trim().is_empty() {
        return Err(AppError::Other("Wallet name is required".into()));
    }
    let pool = state.pool()?;
    repo::rename(pool, id, name.trim()).await?;
    Ok(())
}

#[tauri::command]
pub async fn local_wallet_delete(state: State<'_, AppState>, id: i64) -> Result<(), AppError> {
    let pool = state.pool()?;
    repo::delete(pool, id).await?;
    Ok(())
}

/// Verify the user typed the correct password for a wallet without
/// surfacing the mnemonic. Used by the unlock-on-action UX pattern in
/// the FE (the password prompt before signing).
#[tauri::command]
pub async fn local_wallet_verify_password(state: State<'_, AppState>, id: i64, password: String) -> Result<bool, AppError> {
    let pool = state.pool()?;
    let wallet = match repo::get_by_id(pool, id).await? {
        Some(w) => w,
        None => return Err(AppError::Other(format!("Wallet {id} not found"))),
    };
    let expected = crypto::password_hash(&password, &wallet.address);
    Ok(constant_time_eq(expected.as_bytes(), wallet.password_hash.as_bytes()))
}

/// Decrypt and return a wallet's mnemonic. The FE uses this on the
/// "view recovery phrase" screen after the user re-types their password.
/// Wrong password yields `Err` (the AEAD tag mismatch is indistinguishable
/// from corrupt data at the API surface).
#[tauri::command]
pub async fn local_wallet_get_decrypted_mnemonic(state: State<'_, AppState>, id: i64, password: String) -> Result<String, AppError> {
    let pool = state.pool()?;
    let wallet = match repo::get_by_id(pool, id).await? {
        Some(w) => w,
        None => return Err(AppError::Other(format!("Wallet {id} not found"))),
    };
    // Hash check first for a friendlier error than AEAD-decrypt-failed.
    let expected = crypto::password_hash(&password, &wallet.address);
    if !constant_time_eq(expected.as_bytes(), wallet.password_hash.as_bytes()) {
        return Err(AppError::Other("Incorrect password".into()));
    }
    let plain = crypto::decrypt_mnemonic(&wallet.encrypted_mnemonic, &password, &wallet.address)?;
    Ok(plain.as_str().to_owned())
}

/// Exported backup payload. The FE serialises this to a JSON file the
/// user saves to disk. Re-importing on another device uses
/// `local_wallet_import_encrypted_backup` below.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct WalletBackup {
    pub name: String,
    pub address: String,
    pub encrypted_mnemonic: String,
    pub password_hash: String,
    pub exported_at: String,
}

#[tauri::command]
pub async fn local_wallet_export_backup(state: State<'_, AppState>, id: i64) -> Result<WalletBackup, AppError> {
    let pool = state.pool()?;
    let wallet = match repo::get_by_id(pool, id).await? {
        Some(w) => w,
        None => return Err(AppError::Other(format!("Wallet {id} not found"))),
    };
    use std::time::{SystemTime, UNIX_EPOCH};
    let exported_at = {
        // RFC3339-ish: just emit ms since epoch as a string. The FE displays
        // the file's own mtime so this field is informational only.
        let ms = SystemTime::now().duration_since(UNIX_EPOCH).map(|d| d.as_millis()).unwrap_or(0);
        ms.to_string()
    };
    Ok(WalletBackup {
        name: wallet.name,
        address: wallet.address,
        encrypted_mnemonic: wallet.encrypted_mnemonic,
        password_hash: wallet.password_hash,
        exported_at,
    })
}

/// Import a wallet from the JSON payload produced by `export_backup`. The
/// ciphertext + password hash are stored verbatim — re-encryption is not
/// possible without the password, which the export file does not contain.
#[tauri::command]
pub async fn local_wallet_import_encrypted_backup(
    state: State<'_, AppState>,
    name: String,
    address: String,
    encrypted_mnemonic: String,
    password_hash: String,
) -> Result<PublicLocalWallet, AppError> {
    if name.trim().is_empty() {
        return Err(AppError::Other("Wallet name is required".into()));
    }
    if address.trim().is_empty() {
        return Err(AppError::Other("Address is required".into()));
    }
    let pool = state.pool()?;
    let row = repo::insert(pool, name.trim(), address.trim(), &encrypted_mnemonic, &password_hash).await?;
    Ok(PublicLocalWallet::from(&row))
}

/// Constant-time equality for two byte slices. SHA-256 hex strings are
/// fixed length so the timing channel from `==` is small in practice, but
/// using constant-time eq makes that explicit.
fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut diff: u8 = 0;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

// Convenience: keep the LocalWallet alias importable from this module so
// downstream code can `use crate::wallet::commands::LocalWallet`.
#[allow(dead_code)]
pub(crate) type _LocalWallet = LocalWallet;
