// Small "currently shared via public link" indicator for a drive row.
// Renders nothing for entries that aren't shared, so the caller can drop it
// next to the filename without a guard.
//
// Visual design: a 14px primary-color link icon with a tooltip. The
// icon (not text) was chosen so the badge can fit into both the table
// row's tight name cell and the card view's 40px filename strip
// without bumping the layout. The tooltip body is generated by
// `buildSharedBadgeTooltip` so the single-share / multi-share copy
// stays in one tested place.

"use client";

import { FC } from "react";
import * as Tooltip from "@radix-ui/react-tooltip";
import { Link as LinkIcon } from "lucide-react";

import { useSharedFiles } from "@/app/lib/hooks/useSharedFiles";
import { cn } from "@/lib/utils";
import { buildSharedBadgeTooltip } from "./sharedBadgeTooltip";

interface SharedLinkBadgeProps {
  label: string | null | undefined;
  actualName: string | null | undefined;
  className?: string;
  /**
   * Navigates to share-link management (the `/shares` page) for this file.
   * When provided the badge becomes clickable and stops the click from
   * bubbling to the row/card, whose own click opens the file preview —
   * matching Dropbox/Drive, where the link icon takes you to manage the
   * link, it doesn't open the file (or re-create the share). Omit it to keep
   * the badge display-only.
   */
  onManageShare?: () => void;
}

const SharedLinkBadge: FC<SharedLinkBadgeProps> = ({
  label,
  actualName,
  className,
  onManageShare,
}) => {
  const { getSharesFor } = useSharedFiles();

  // Folders CAN be shared now (`hcfs_create_folder_share` zips one and records
  // the same `share_origin` row a file gets), so the badge is no longer
  // suppressed for them.
  //
  // KNOWN LIMITATION: the lookup key is this row's `actualName`, which for a
  // NESTED folder row is only the basename while the origin row stores the full
  // drive-relative path — so a shared subfolder shows no badge. Files are
  // unaffected (their `actualName` is already the full path). This is the same
  // cosmetic-miss posture `shares/origin.rs` documents for NFD/NFC drift: the
  // share itself is fine, only the badge is absent.
  const rows = getSharesFor(label, actualName);
  const tooltipLines = buildSharedBadgeTooltip(rows);
  // `buildSharedBadgeTooltip` returns null for unshared files, which
  // doubles as the "don't render the badge" signal.
  if (!tooltipLines) return null;

  const interactive = !!onManageShare;

  // Open share management, and — crucially — stop the click from reaching the
  // row/card, whose own handler opens the file preview. preventDefault guards
  // against the badge sitting inside a preview <button> trigger.
  const handleActivate = (
    e: React.MouseEvent | React.KeyboardEvent,
  ) => {
    e.stopPropagation();
    e.preventDefault();
    onManageShare?.();
  };

  const triggerClassName = cn(
    "inline-flex items-center justify-center text-primary-50 flex-shrink-0",
    "bg-primary-95 rounded-full px-1 pt-1",
    interactive &&
      "cursor-pointer transition-colors hover:bg-primary-90 hover:text-primary-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-50/40",
    className,
  );

  return (
    <Tooltip.Provider delayDuration={200}>
      <Tooltip.Root>
        <Tooltip.Trigger asChild>
          {/* role=button (not a real <button>) because the badge can render
              inside the row's preview <button> trigger — a nested <button>
              breaks hydration. Space/Enter mirror a native button. */}
          <span
            className={triggerClassName}
            aria-label={
              interactive ? "Manage share link" : "Shared via public link"
            }
            {...(interactive
              ? {
                  role: "button",
                  tabIndex: 0,
                  onClick: handleActivate,
                  onKeyDown: (e: React.KeyboardEvent) => {
                    if (e.key === "Enter" || e.key === " ") handleActivate(e);
                  },
                }
              : {})}
          >
            <LinkIcon className="size-3.5" />
          </span>
        </Tooltip.Trigger>
        <Tooltip.Portal>
          <Tooltip.Content
            side="top"
            sideOffset={4}
            // Light base + the shared dark-tooltip treatment from CustomTooltip2
            // (dark surface, hairline border/ring, deeper shadow) so it reads as
            // a first-class tooltip in dark mode instead of a glaring white card.
            className={cn(
              "z-50 bg-white border border-grey-80 rounded-[0.5rem] px-3 py-2 text-xs font-medium text-grey-40 shadow-lg",
              "dark:border-white/10 dark:bg-[#1c1c1e] dark:text-grey-dark-100",
              "dark:shadow-[0_8px_28px_-8px_rgba(0,0,0,0.55)] dark:ring-1 dark:ring-inset dark:ring-white/[0.04]",
            )}
          >
            {tooltipLines.map((line, i) => (
              <div key={i}>{line}</div>
            ))}
            {interactive && (
              <div className="mt-1 text-grey-60 dark:text-grey-dark-80">
                Click to manage link
              </div>
            )}
            <Tooltip.Arrow className="fill-white dark:fill-[#1c1c1e]" />
          </Tooltip.Content>
        </Tooltip.Portal>
      </Tooltip.Root>
    </Tooltip.Provider>
  );
};

export default SharedLinkBadge;
