import { VMTemplate } from "./vm-template-card";

export const MOCK_VM_TEMPLATES: VMTemplate[] = [
  {
    id: "template-1",
    name: "Hippus Model R3-16",
    ram: "RAM",
    ramValue: "16 GB RAM",
    cores: "Cores",
    coresValue: "2 vCores (2.3 GHz)",
    storage: "50 GB NVMe",
    bandwidth: "500 MBit/s",
    price: "$ 4.13/per hour",
    category: "general",
  },
  {
    id: "template-2",
    name: "Hippus Model R3-16",
    ram: "RAM",
    ramValue: "16 GB RAM",
    cores: "Cores",
    coresValue: "2 vCores (2.3 GHz)",
    storage: "50 GB NVMe",
    bandwidth: "500 MBit/s",
    price: "$ 4.13/per hour",
    category: "general",
  },
  {
    id: "template-3",
    name: "Hippus Model R3-16",
    ram: "RAM",
    ramValue: "16 GB RAM",
    cores: "Cores",
    coresValue: "2 vCores (2.3 GHz)",
    storage: "50 GB NVMe",
    bandwidth: "500 MBit/s",
    price: "$ 4.13/per hour",
    category: "compute",
  },
  {
    id: "template-4",
    name: "Hippus Model R3-16",
    ram: "RAM",
    ramValue: "16 GB RAM",
    cores: "Cores",
    coresValue: "2 vCores (2.3 GHz)",
    storage: "50 GB NVMe",
    bandwidth: "500 MBit/s",
    price: "$ 4.13/per hour",
    category: "memory",
  },
  {
    id: "template-5",
    name: "Hippus Model R3-16",
    ram: "RAM",
    ramValue: "16 GB RAM",
    cores: "Cores",
    coresValue: "2 vCores (2.3 GHz)",
    storage: "50 GB NVMe",
    bandwidth: "500 MBit/s",
    price: "$ 4.13/per hour",
    category: "discovery",
  },
  {
    id: "template-6",
    name: "Hippus Model R3-16",
    ram: "RAM",
    ramValue: "16 GB RAM",
    cores: "Cores",
    coresValue: "2 vCores (2.3 GHz)",
    storage: "50 GB NVMe",
    bandwidth: "500 MBit/s",
    price: "$ 4.13/per hour",
    category: "storage",
  },
  {
    id: "template-7",
    name: "Hippus Model R3-16",
    ram: "RAM",
    ramValue: "16 GB RAM",
    cores: "Cores",
    coresValue: "2 vCores (2.3 GHz)",
    storage: "50 GB NVMe",
    bandwidth: "500 MBit/s",
    price: "$ 4.13/per hour",
    category: "general",
  },
  {
    id: "template-8",
    name: "Hippus Model R3-16",
    ram: "RAM",
    ramValue: "16 GB RAM",
    cores: "Cores",
    coresValue: "2 vCores (2.3 GHz)",
    storage: "50 GB NVMe",
    bandwidth: "500 MBit/s",
    price: "$ 4.13/per hour",
    category: "compute",
  },
];
