// Small "currently shared via public link" indicator for a file row.
// Renders nothing for files that aren't shared or for folders, so the
// caller can drop it next to the filename without a guard.
//
// Visual design: a 14px primary-color link icon with a tooltip. The
// icon (not text) was chosen so the badge can fit into both the table
// row's tight name cell and the card view's 40px filename strip
// without bumping the layout. The tooltip body is generated by
// `buildSharedBadgeTooltip` so the single-share / multi-share copy
// stays in one tested place.

"use client";

import { FC } from "react";
import * as Tooltip from "@radix-ui/react-tooltip";
import { Link as LinkIcon } from "lucide-react";

import { useSharedFiles } from "@/app/lib/hooks/useSharedFiles";
import { cn } from "@/lib/utils";
import { buildSharedBadgeTooltip } from "./sharedBadgeTooltip";

interface SharedLinkBadgeProps {
  label: string | null | undefined;
  actualName: string | null | undefined;
  isFolder?: boolean;
  className?: string;
}

const SharedLinkBadge: FC<SharedLinkBadgeProps> = ({ label, actualName, isFolder, className }) => {
  const { getSharesFor } = useSharedFiles();

  // Folders don't go through `hcfs_create_share` (the Rust path
  // rejects directories), so a folder can never be shared.
  if (isFolder) return null;

  const rows = getSharesFor(label, actualName);
  const tooltipLines = buildSharedBadgeTooltip(rows);
  // `buildSharedBadgeTooltip` returns null for unshared files, which
  // doubles as the "don't render the badge" signal.
  if (!tooltipLines) return null;

  return (
    <Tooltip.Provider delayDuration={200}>
      <Tooltip.Root>
        <Tooltip.Trigger asChild>
          <span
            className={cn(
              "inline-flex items-center justify-center text-primary-50 flex-shrink-0",
              "bg-primary-95 rounded-full p-1",
              className
            )}
            aria-label="Shared via public link"
          >
            <LinkIcon className="size-4" />
          </span>
        </Tooltip.Trigger>
        <Tooltip.Portal>
          <Tooltip.Content
            side="top"
            sideOffset={4}
            className="z-50 bg-white border border-grey-80 rounded-[0.5rem] px-3 py-2 text-xs font-medium text-grey-40 shadow-lg"
          >
            {tooltipLines.map((line, i) => (
              <div key={i}>{line}</div>
            ))}
            <Tooltip.Arrow className="fill-white" />
          </Tooltip.Content>
        </Tooltip.Portal>
      </Tooltip.Root>
    </Tooltip.Provider>
  );
};

export default SharedLinkBadge;
