use crate::sync_shared::{is_cancelled, HCFS_SYNC_STATE};
use hcfs_client::client::HcfsClientConfig;
use hcfs_client::drive::Drive;
use hcfs_client::sync::{SyncMode, SyncOutcome, SyncPlan, SyncProgress};
use notify::{RecommendedWatcher, RecursiveMode, Watcher};
use once_cell::sync::Lazy;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::{Duration, Instant};
use tauri::{AppHandle, Emitter};
use tokio::sync::Mutex;
use tokio::task::JoinHandle;

/// Flag to suppress file watcher events while a sync is in progress,
/// preventing a feedback loop where sync-generated file changes trigger more syncs.
static SYNC_IN_PROGRESS: Lazy<Arc<AtomicBool>> = Lazy::new(|| Arc::new(AtomicBool::new(false)));

pub struct HcfsDriveManager {
    drive: Drive,
    sync_path: PathBuf,
}

impl HcfsDriveManager {
    pub fn new(sync_path: PathBuf) -> Self {
        Self {
            drive: Drive::new(&sync_path),
            sync_path,
        }
    }

    pub fn init(&mut self, password: &str, mnemonic: Option<&str>) -> Result<String, String> {
        self.drive.init(password, mnemonic).map_err(|e| e.to_string())
    }

    pub fn unlock(&mut self, password: &str) -> Result<String, String> {
        self.drive.unlock(password).map_err(|e| e.to_string())?;
        self.drive
            .user_id()
            .map(|s| s.to_string())
            .ok_or_else(|| "Failed to get user_id after unlock".to_string())
    }

    pub fn is_unlocked(&self) -> bool {
        self.drive.is_unlocked()
    }
    pub fn is_initialized(&self) -> bool {
        self.drive.is_initialized()
    }
    #[allow(dead_code)]
    pub fn user_id(&self) -> Option<&str> {
        self.drive.user_id()
    }
    pub fn sync_path(&self) -> &Path {
        &self.sync_path
    }

    pub fn set_config(&mut self, config: HcfsClientConfig) -> Result<(), String> {
        self.drive.set_config(config).map_err(|e| e.to_string())
    }

    pub fn set_progress(&mut self, progress: SyncProgress) {
        self.drive.set_progress_handlers(progress);
    }

    pub async fn sync(&mut self) -> Result<SyncOutcome, String> {
        self.drive
            .sync_async(SyncMode::NonInteractive)
            .await
            .map_err(|e| e.to_string())
    }

    #[allow(dead_code)]
    pub fn stage(&self) -> Result<SyncPlan, String> {
        self.drive.stage().map_err(|e| e.to_string())
    }

    pub fn cleanup_temp(&self) {
        self.drive.cleanup_stale_temp_files();
    }
}

/// Global Drive instance
pub static HCFS_DRIVE: Lazy<Arc<Mutex<Option<HcfsDriveManager>>>> =
    Lazy::new(|| Arc::new(Mutex::new(None)));

/// Handle for the background sync loop task so we can abort it before starting a new one.
pub static SYNC_LOOP_HANDLE: Lazy<Arc<Mutex<Option<JoinHandle<()>>>>> =
    Lazy::new(|| Arc::new(Mutex::new(None)));

/// Heartbeat interval: sync every 30 seconds regardless of local changes
const HEARTBEAT_SECS: u64 = 30;

/// Debounce interval: wait 5 seconds after local changes before syncing
const DEBOUNCE_SECS: u64 = 5;

/// Start background sync loop
pub async fn start_sync_loop(app: AppHandle) {
    println!("[Sync] Starting sync loop...");

    // Abort the previous sync loop if one is still running
    {
        let mut handle_guard = SYNC_LOOP_HANDLE.lock().await;
        if let Some(prev) = handle_guard.take() {
            println!("[Sync] Aborting previous sync loop task");
            prev.abort();
        }
    }

    let sync_path = {
        let guard = HCFS_DRIVE.lock().await;
        guard.as_ref().map(|m| m.sync_path().to_path_buf())
    };

    let Some(sync_path) = sync_path else {
        println!("[Sync] Drive not available, sync loop not started");
        return;
    };

    println!("[Sync] Watching sync path: {:?}", sync_path);

    let (tx, mut rx) = tokio::sync::mpsc::channel::<()>(256);

    // File watcher — suppressed during active sync to avoid feedback loops
    let tx_clone = tx.clone();
    let sync_flag = SYNC_IN_PROGRESS.clone();
    let mut watcher: RecommendedWatcher =
        notify::recommended_watcher(move |res: Result<notify::Event, notify::Error>| {
            if sync_flag.load(Ordering::Relaxed) {
                return; // Ignore events generated by an ongoing sync
            }
            if let Ok(_event) = res {
                let _ = tx_clone.blocking_send(());
            }
        })
        .expect("Failed to create watcher");

    watcher
        .watch(&sync_path, RecursiveMode::Recursive)
        .expect("Failed to watch path");

    let handle = tokio::spawn(async move {
        let _watcher = watcher; // keep alive

        // Clean up any stale temp files from previous runs
        {
            let guard = HCFS_DRIVE.lock().await;
            if let Some(manager) = guard.as_ref() {
                manager.cleanup_temp();
            }
        }

        // Initial sync on startup
        println!("[Sync] Running initial sync...");
        trigger_sync(&app).await;

        let mut debounce = tokio::time::interval(Duration::from_secs(DEBOUNCE_SECS));
        let mut has_changes = false;
        let mut last_sync = Instant::now();

        loop {
            if is_cancelled() {
                break;
            }

            tokio::select! {
                msg = rx.recv() => {
                    if msg.is_none() { break; }
                    has_changes = true;
                }
                _ = debounce.tick() => {
                    let heartbeat_due = last_sync.elapsed() >= Duration::from_secs(HEARTBEAT_SECS);
                    if has_changes || heartbeat_due {
                        has_changes = false;
                        trigger_sync(&app).await;
                        last_sync = Instant::now();
                    }
                }
            }
        }
        println!("[Sync] Sync loop exited");
    });

    // Store the handle so we can abort it later
    {
        let mut handle_guard = SYNC_LOOP_HANDLE.lock().await;
        *handle_guard = Some(handle);
    }
}

/// Execute one sync cycle
pub async fn trigger_sync(app: &AppHandle) {
    {
        let mut s = HCFS_SYNC_STATE.lock().unwrap();
        if s.is_syncing {
            println!("[Sync] Sync already in progress, skipping");
            return;
        }
        s.is_syncing = true;
    }

    // Suppress file watcher events during sync to prevent feedback loops
    SYNC_IN_PROGRESS.store(true, Ordering::Relaxed);

    println!("[Sync] Starting sync cycle...");
    let _ = app.emit("hcfs_sync_started", ());

    let result = {
        let mut guard = HCFS_DRIVE.lock().await;
        match guard.as_mut() {
            Some(m) if m.is_unlocked() => {
                println!("[Sync] Drive is unlocked, executing sync...");
                Some(m.sync().await)
            }
            Some(_) => {
                println!("[Sync] Drive exists but is not unlocked");
                None
            }
            None => {
                println!("[Sync] Drive not available (None)");
                None
            }
        }
    };

    // Re-enable file watcher after a short delay to ignore trailing FS events
    let flag = SYNC_IN_PROGRESS.clone();
    tokio::spawn(async move {
        tokio::time::sleep(Duration::from_secs(2)).await;
        flag.store(false, Ordering::Relaxed);
    });

    {
        let mut s = HCFS_SYNC_STATE.lock().unwrap();
        s.is_syncing = false;
        s.last_sync_time = Some(chrono::Utc::now().timestamp());
    }

    match result {
        Some(Ok(outcome)) => {
            println!(
                "[Sync] Sync completed: uploaded={}, downloaded={}, deleted_local={}, deleted_remote={}, conflicts_resolved={}, conflicts_skipped={}",
                outcome.files_uploaded,
                outcome.files_downloaded,
                outcome.files_deleted_locally,
                outcome.files_deleted_remotely,
                outcome.conflicts_resolved,
                outcome.conflicts_skipped,
            );

            // Note: uploads/downloads are tracked individually via progress callbacks
            // in setup_progress_handlers (syncing.rs). Deletes are not tracked here
            // because SyncOutcome only provides counts, not individual filenames.

            let _ = app.emit(
                "hcfs_sync_completed",
                serde_json::json!({
                    "files_uploaded": outcome.files_uploaded,
                    "files_downloaded": outcome.files_downloaded,
                    "files_deleted_locally": outcome.files_deleted_locally,
                    "files_deleted_remotely": outcome.files_deleted_remotely,
                    "conflicts_resolved": outcome.conflicts_resolved,
                    "conflicts_skipped": outcome.conflicts_skipped,
                }),
            );
        }
        Some(Err(e)) => {
            println!("[Sync] Sync failed with error: {}", e);
            let _ = app.emit("hcfs_sync_error", serde_json::json!({"error": e}));
        }
        None => {
            println!("[Sync] Drive not available or not unlocked, skipping sync");
            let _ = app.emit(
                "hcfs_sync_error",
                serde_json::json!({"error": "Drive not initialized or not unlocked"}),
            );
        }
    }
}
